
[window]
dimensions = {columns = 120, lines = 40}
padding = {x = 4, y = 4}

opacity = 0.95
title = "genshin is cringe"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = {family = "FiraCode Nerd Font Mono", style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono", style = "Italic"}
bold_italic = {family = "FiraCode Nerd Font Mono", style = "Bold Italic"}
size = 14

[mouse]
hide_when_typing = true
